/*

    1. Executar Scripts.sql;
    2. Executar ScriptFuncion.sql;
    3. Executar ScriptTrigger.sql;
    4. Executar ScriptView.sql;

    Entrar no sistema precisa funcionar tudo, principalmente as permissões com tudo liberado;

*/

--POPULA BANCO;
SELECT fnDisableAuditoria();

DELETE FROM FASE;
DELETE FROM VERSAO;
DELETE FROM MOTIVO;
DELETE FROM MODULO;
DELETE FROM PROJETO;
DELETE FROM PRIORIDADE;
DELETE FROM CLIENTE;
DELETE FROM CIDADE;
DELETE FROM USUARIO_PERMISSAO_TELA_ACOES;
DELETE FROM USUARIO_PERMISSAO_TELA;
DELETE FROM ENVIO_EMAIL;
DELETE FROM AUDITORIA;
INSERT INTO FASE(ID,DESCRICAO,SITUACAO) VALUES (1,'FASE','A');
INSERT INTO MOTIVO(ID,DESCRICAO,SITUACAO) VALUES (1,'MOTIVO','A');
INSERT INTO PROJETO(ID,DESCRICAO,SITUACAO) VALUES (1,'PROJETO','A');
INSERT INTO PRIORIDADE(ID,DESCRICAO,SITUACAO) VALUES (1,'PRIORIDADE','A');
INSERT INTO MODULO(ID,ID_PROJETO,DESCRICAO,SITUACAO) VALUES (1,1,'MODULO','A');
INSERT INTO VERSAO(ID,ID_PROJETO,DESCRICAO,SITUACAO) VALUES (1,1,'VERSAO','A');
INSERT INTO CIDADE(ID,DESCRICAO,SITUACAO) VALUES (1,'CIDADE','A');
INSERT INTO CLIENTE(ID,ID_CIDADE,RAZAO_SOCIAL,CPF_CNPJ,TIPO_CADASTRO,CLIENTECOL,ENDERECO,TELEFONE,SITUACAO,EMAIL) VALUES (1,1,'CLIENTE','11111111111','F','','TESTE','11111111111','A','TESTE@TESTE.COM.BR');
