package entidade;
// Generated 17/10/2017 22:28:34 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String tabela;
     private Date dataHora;
     private char tipo;
     private Serializable campos;

    public Auditoria() {
    }

	
    public Auditoria(int id, Usuario usuario, String tabela, char tipo) {
        this.id = id;
        this.usuario = usuario;
        this.tabela = tabela;
        this.tipo = tipo;
    }
    public Auditoria(int id, Usuario usuario, String tabela, Date dataHora, char tipo, Serializable campos) {
       this.id = id;
       this.usuario = usuario;
       this.tabela = tabela;
       this.dataHora = dataHora;
       this.tipo = tipo;
       this.campos = campos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTabela() {
        return this.tabela;
    }
    
    public void setTabela(String tabela) {
        this.tabela = tabela;
    }
    public Date getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public Serializable getCampos() {
        return this.campos;
    }
    
    public void setCampos(Serializable campos) {
        this.campos = campos;
    }




}


