package entidade;
// Generated 07/08/2017 21:08:37 by Hibernate Tools 4.3.1



/**
 * Auditoria generated by hbm2java
 */
public class Auditoria  implements java.io.Serializable {


     private int id;
     private Usuario usuario;

    public Auditoria() {
    }

    public Auditoria(int id, Usuario usuario) {
       this.id = id;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


