package entidade;
// Generated 23/10/2017 22:08:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EnvioEmail generated by hbm2java
 */
@Entity
@Table(name="envio_email"
    ,schema="public"
)
public class EnvioEmail  implements java.io.Serializable {


     private int id;
     private int dominio;
     private String email;
     private String senha;
     private String titulo;
     private String mensagem;
     private Character envioAtivo;

    public EnvioEmail() {
    }

	
    public EnvioEmail(int id, int dominio, String email, String senha, String titulo) {
        this.id = id;
        this.dominio = dominio;
        this.email = email;
        this.senha = senha;
        this.titulo = titulo;
    }
    public EnvioEmail(int id, int dominio, String email, String senha, String titulo, String mensagem, Character envioAtivo) {
       this.id = id;
       this.dominio = dominio;
       this.email = email;
       this.senha = senha;
       this.titulo = titulo;
       this.mensagem = mensagem;
       this.envioAtivo = envioAtivo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="dominio", nullable=false, length=1)
    public int getDominio() {
        return this.dominio;
    }
    
    public void setDominio(int dominio) {
        this.dominio = dominio;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="senha", nullable=false, length=100)
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }

    
    @Column(name="titulo", nullable=false, length=250)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="mensagem")
    public String getMensagem() {
        return this.mensagem;
    }
    
    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    
    @Column(name="envio_ativo", length=1)
    public Character getEnvioAtivo() {
        return this.envioAtivo;
    }
    
    public void setEnvioAtivo(Character envioAtivo) {
        this.envioAtivo = envioAtivo;
    }




}


