package entidade;
// Generated 21/11/2017 19:22:12 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MovimentoTarefa generated by hbm2java
 */
public class MovimentoTarefa  implements java.io.Serializable {


     private int id;
     private Tarefa tarefa;
     private Usuario usuario;
     private String descricao;
     private Date datahoraMovimento;
     private char situacao;
     private String anexo;

    public MovimentoTarefa() {
    }
    
    public MovimentoTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }

	
    public MovimentoTarefa(int id, Tarefa tarefa, Usuario usuario, String descricao, char situacao) {
        this.id = id;
        this.tarefa = tarefa;
        this.usuario = usuario;
        this.descricao = descricao;
        this.situacao = situacao;
    }
    public MovimentoTarefa(int id, Tarefa tarefa, Usuario usuario, String descricao, Date datahoraMovimento, char situacao, String anexo) {
       this.id = id;
       this.tarefa = tarefa;
       this.usuario = usuario;
       this.descricao = descricao;
       this.datahoraMovimento = datahoraMovimento;
       this.situacao = situacao;
       this.anexo = anexo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tarefa getTarefa() {
        return this.tarefa;
    }
    
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDatahoraMovimento() {
        return this.datahoraMovimento;
    }
    
    public void setDatahoraMovimento(Date datahoraMovimento) {
        this.datahoraMovimento = datahoraMovimento;
    }
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }
    public String getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(String anexo) {
        this.anexo = anexo;
    }




}


