package entidade;
// Generated 17/10/2017 22:28:34 by Hibernate Tools 4.3.1



/**
 * Telas generated by hbm2java
 */
public class Telas  implements java.io.Serializable {


     private long id;
     private String tela;
     private String telaAmigavel;
     private String acao;
     private String acaoAmigavel;

    public Telas() {
    }

    public Telas(long id, String tela, String telaAmigavel, String acao, String acaoAmigavel) {
       this.id = id;
       this.tela = tela;
       this.telaAmigavel = telaAmigavel;
       this.acao = acao;
       this.acaoAmigavel = acaoAmigavel;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getTela() {
        return this.tela;
    }
    
    public void setTela(String tela) {
        this.tela = tela;
    }
    public String getTelaAmigavel() {
        return this.telaAmigavel;
    }
    
    public void setTelaAmigavel(String telaAmigavel) {
        this.telaAmigavel = telaAmigavel;
    }
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }
    public String getAcaoAmigavel() {
        return this.acaoAmigavel;
    }
    
    public void setAcaoAmigavel(String acaoAmigavel) {
        this.acaoAmigavel = acaoAmigavel;
    }




}


