package entidade;
// Generated 22/09/2017 22:10:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioPermissaoTela generated by hbm2java
 */
@Entity
@Table(name="usuario_permissao_tela"
    ,schema="public"
)
public class UsuarioPermissaoTela  implements java.io.Serializable {


     private long id;
     private Usuario usuario;
     private String tela;
     private String telaAmigavel;
     private boolean permiteAcesso;
     private Set usuarioPermissaoTelaAcoeses = new HashSet(0);

    public UsuarioPermissaoTela() {
    }

	
    public UsuarioPermissaoTela(long id, Usuario usuario, String tela, String telaAmigavel, boolean permiteAcesso) {
        this.id = id;
        this.usuario = usuario;
        this.tela = tela;
        this.telaAmigavel = telaAmigavel;
        this.permiteAcesso = permiteAcesso;
    }
    public UsuarioPermissaoTela(long id, Usuario usuario, String tela, String telaAmigavel, boolean permiteAcesso, Set usuarioPermissaoTelaAcoeses) {
       this.id = id;
       this.usuario = usuario;
       this.tela = tela;
       this.telaAmigavel = telaAmigavel;
       this.permiteAcesso = permiteAcesso;
       this.usuarioPermissaoTelaAcoeses = usuarioPermissaoTelaAcoeses;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="tela", nullable=false, length=100)
    public String getTela() {
        return this.tela;
    }
    
    public void setTela(String tela) {
        this.tela = tela;
    }

    
    @Column(name="tela_amigavel", nullable=false, length=100)
    public String getTelaAmigavel() {
        return this.telaAmigavel;
    }
    
    public void setTelaAmigavel(String telaAmigavel) {
        this.telaAmigavel = telaAmigavel;
    }

    
    @Column(name="permite_acesso", nullable=false, length=1)
    public boolean isPermiteAcesso() {
        return this.permiteAcesso;
    }
    
    public void setPermiteAcesso(boolean permiteAcesso) {
        this.permiteAcesso = permiteAcesso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarioPermissaoTela")
    public Set getUsuarioPermissaoTelaAcoeses() {
        return this.usuarioPermissaoTelaAcoeses;
    }
    
    public void setUsuarioPermissaoTelaAcoeses(Set usuarioPermissaoTelaAcoeses) {
        this.usuarioPermissaoTelaAcoeses = usuarioPermissaoTelaAcoeses;
    }




}


