package entidade;
// Generated 17/10/2017 22:28:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioPermissaoTela generated by hbm2java
 */
public class UsuarioPermissaoTela  implements java.io.Serializable {


     private long id;
     private Usuario usuario;
     private String tela;
     private String telaAmigavel;
     private boolean permiteAcesso;
     private Set usuarioPermissaoTelaAcoeses = new HashSet(0);

    public UsuarioPermissaoTela() {
    }

	
    public UsuarioPermissaoTela(long id, Usuario usuario, String tela, String telaAmigavel, boolean permiteAcesso) {
        this.id = id;
        this.usuario = usuario;
        this.tela = tela;
        this.telaAmigavel = telaAmigavel;
        this.permiteAcesso = permiteAcesso;
    }
    public UsuarioPermissaoTela(long id, Usuario usuario, String tela, String telaAmigavel, boolean permiteAcesso, Set usuarioPermissaoTelaAcoeses) {
       this.id = id;
       this.usuario = usuario;
       this.tela = tela;
       this.telaAmigavel = telaAmigavel;
       this.permiteAcesso = permiteAcesso;
       this.usuarioPermissaoTelaAcoeses = usuarioPermissaoTelaAcoeses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTela() {
        return this.tela;
    }
    
    public void setTela(String tela) {
        this.tela = tela;
    }
    public String getTelaAmigavel() {
        return this.telaAmigavel;
    }
    
    public void setTelaAmigavel(String telaAmigavel) {
        this.telaAmigavel = telaAmigavel;
    }
    public boolean isPermiteAcesso() {
        return this.permiteAcesso;
    }
    
    public void setPermiteAcesso(boolean permiteAcesso) {
        this.permiteAcesso = permiteAcesso;
    }
    public Set getUsuarioPermissaoTelaAcoeses() {
        return this.usuarioPermissaoTelaAcoeses;
    }
    
    public void setUsuarioPermissaoTelaAcoeses(Set usuarioPermissaoTelaAcoeses) {
        this.usuarioPermissaoTelaAcoeses = usuarioPermissaoTelaAcoeses;
    }




}


