package entidade;
// Generated 15/09/2017 21:15:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioPermissaoTela generated by hbm2java
 */
public class UsuarioPermissaoTela  implements java.io.Serializable {


     private long id;
     private Usuario usuario;
     private String tela;
     private char permiteAcesso;
     private Set usuarioPermissaoTelaAcoeses = new HashSet(0);

    public UsuarioPermissaoTela() {
    }

	
    public UsuarioPermissaoTela(long id, Usuario usuario, String tela, char permiteAcesso) {
        this.id = id;
        this.usuario = usuario;
        this.tela = tela;
        this.permiteAcesso = permiteAcesso;
    }
    public UsuarioPermissaoTela(long id, Usuario usuario, String tela, char permiteAcesso, Set usuarioPermissaoTelaAcoeses) {
       this.id = id;
       this.usuario = usuario;
       this.tela = tela;
       this.permiteAcesso = permiteAcesso;
       this.usuarioPermissaoTelaAcoeses = usuarioPermissaoTelaAcoeses;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTela() {
        return this.tela;
    }
    
    public void setTela(String tela) {
        this.tela = tela;
    }
    public char getPermiteAcesso() {
        return this.permiteAcesso;
    }
    
    public void setPermiteAcesso(char permiteAcesso) {
        this.permiteAcesso = permiteAcesso;
    }
    public Set getUsuarioPermissaoTelaAcoeses() {
        return this.usuarioPermissaoTelaAcoeses;
    }
    
    public void setUsuarioPermissaoTelaAcoeses(Set usuarioPermissaoTelaAcoeses) {
        this.usuarioPermissaoTelaAcoeses = usuarioPermissaoTelaAcoeses;
    }




}


