package entidade;
// Generated 22/09/2017 22:10:23 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioPermissaoTelaAcoes generated by hbm2java
 */
@Entity
@Table(name="usuario_permissao_tela_acoes"
    ,schema="public"
)
public class UsuarioPermissaoTelaAcoes  implements java.io.Serializable {


     private long id;
     private UsuarioPermissaoTela usuarioPermissaoTela;
     private String acao;
     private String acaoAmigavel;
     private boolean permiteAcesso;

    public UsuarioPermissaoTelaAcoes() {
    }

    public UsuarioPermissaoTelaAcoes(long id, UsuarioPermissaoTela usuarioPermissaoTela, String acao, String acaoAmigavel, boolean permiteAcesso) {
       this.id = id;
       this.usuarioPermissaoTela = usuarioPermissaoTela;
       this.acao = acao;
       this.acaoAmigavel = acaoAmigavel;
       this.permiteAcesso = permiteAcesso;
    }
   
     @Id 

    
    @Column(name="id", nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tela", nullable=false)
    public UsuarioPermissaoTela getUsuarioPermissaoTela() {
        return this.usuarioPermissaoTela;
    }
    
    public void setUsuarioPermissaoTela(UsuarioPermissaoTela usuarioPermissaoTela) {
        this.usuarioPermissaoTela = usuarioPermissaoTela;
    }

    
    @Column(name="acao", nullable=false, length=100)
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }

    
    @Column(name="acao_amigavel", nullable=false, length=100)
    public String getAcaoAmigavel() {
        return this.acaoAmigavel;
    }
    
    public void setAcaoAmigavel(String acaoAmigavel) {
        this.acaoAmigavel = acaoAmigavel;
    }

    
    @Column(name="permite_acesso", nullable=false, length=1)
    public boolean isPermiteAcesso() {
        return this.permiteAcesso;
    }
    
    public void setPermiteAcesso(boolean permiteAcesso) {
        this.permiteAcesso = permiteAcesso;
    }




}


