package entidade;
// Generated 20/09/2017 22:24:06 by Hibernate Tools 4.3.1



/**
 * UsuarioPermissaoTelaAcoes generated by hbm2java
 */
public class UsuarioPermissaoTelaAcoes  implements java.io.Serializable {


     private long id;
     private UsuarioPermissaoTela usuarioPermissaoTela;
     private String acao;
     private String acaoAmigavel;
     private char permiteAcesso;

    public UsuarioPermissaoTelaAcoes() {
    }

    public UsuarioPermissaoTelaAcoes(long id, UsuarioPermissaoTela usuarioPermissaoTela, String acao, String acaoAmigavel, char permiteAcesso) {
       this.id = id;
       this.usuarioPermissaoTela = usuarioPermissaoTela;
       this.acao = acao;
       this.acaoAmigavel = acaoAmigavel;
       this.permiteAcesso = permiteAcesso;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public UsuarioPermissaoTela getUsuarioPermissaoTela() {
        return this.usuarioPermissaoTela;
    }
    
    public void setUsuarioPermissaoTela(UsuarioPermissaoTela usuarioPermissaoTela) {
        this.usuarioPermissaoTela = usuarioPermissaoTela;
    }
    public String getAcao() {
        return this.acao;
    }
    
    public void setAcao(String acao) {
        this.acao = acao;
    }
    public String getAcaoAmigavel() {
        return this.acaoAmigavel;
    }
    
    public void setAcaoAmigavel(String acaoAmigavel) {
        this.acaoAmigavel = acaoAmigavel;
    }
    public char getPermiteAcesso() {
        return this.permiteAcesso;
    }
    
    public void setPermiteAcesso(char permiteAcesso) {
        this.permiteAcesso = permiteAcesso;
    }




}


