package entidade;
// Generated 15/09/2017 20:09:58 by Hibernate Tools 4.3.1



/**
 * UsuarioPermissao generated by hbm2java
 */
public class UsuarioPermissao  implements java.io.Serializable {


     private long id;
     private int idUsuario;
     private String tabela;
     private char permiteIncluir;
     private char permiteAlterar;
     private char permiteExcluir;
     private char permiteConsultar;

    public UsuarioPermissao() {
    }

    public UsuarioPermissao(long id, int idUsuario, String tabela, char permiteIncluir, char permiteAlterar, char permiteExcluir, char permiteConsultar) {
       this.id = id;
       this.idUsuario = idUsuario;
       this.tabela = tabela;
       this.permiteIncluir = permiteIncluir;
       this.permiteAlterar = permiteAlterar;
       this.permiteExcluir = permiteExcluir;
       this.permiteConsultar = permiteConsultar;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getTabela() {
        return this.tabela;
    }
    
    public void setTabela(String tabela) {
        this.tabela = tabela;
    }
    public char getPermiteIncluir() {
        return this.permiteIncluir;
    }
    
    public void setPermiteIncluir(char permiteIncluir) {
        this.permiteIncluir = permiteIncluir;
    }
    public char getPermiteAlterar() {
        return this.permiteAlterar;
    }
    
    public void setPermiteAlterar(char permiteAlterar) {
        this.permiteAlterar = permiteAlterar;
    }
    public char getPermiteExcluir() {
        return this.permiteExcluir;
    }
    
    public void setPermiteExcluir(char permiteExcluir) {
        this.permiteExcluir = permiteExcluir;
    }
    public char getPermiteConsultar() {
        return this.permiteConsultar;
    }
    
    public void setPermiteConsultar(char permiteConsultar) {
        this.permiteConsultar = permiteConsultar;
    }




}


