/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import DAO.PermissoesDAO;
import DAO.UsuarioDAO;
import DAO.UsuarioPermissaoTelaAcoesDAO;
import apoio.Validacao;
import controle.ControleCidade;
import entidade.Cidade;
import entidade.Usuario;
import entidade.UsuarioPermissaoTela;
import entidade.UsuarioPermissaoTelaAcoes;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mileto
 */
public class JdgPermissoesUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JdgCadastroCidade
     */
    Cidade cidade;
    Usuario usuarios = new Usuario();
    long idJdgCadastroCidade;
    long idJdgCadastroCliente;
    long idJdgAlteracaoSenha;
    long idJdgParametrosSistema;
    long idJdgCadastroFase;
    long idJdgCadastroProjeto;
    long idJdgCadastroMotivo;
    long idJdgCadastroUsuario;
    long idJdgCadastroPrioridade;
    long idJdgPermissoesUsuario;
    long idBtnSalvarJdgCadastroCidade;
    long idBtnExcluirJdgCadastroCidade;
    long idBtnLocalizarJdgCadastroCidade;
    long idBtnSalvarJdgCadastroCliente;
    long idBtnExcluirJdgCadastroCliente;
    long idBtnLocalizarJdgCadastroCliente;
    long idBtnSalvarJdgAlteracaoSenha;
    long idBtnEnableAuditoriaParametrosSistema;
    long idBtnDisableAuditoriaParametrosSistema;
    long idBtnSalvarJdgCadastroProjeto;
    long idBtnExcluirJdgCadastroProjeto;
    long idBtnLocalizarJdgCadastroProjeto;
    long idBtnSalvarJdgCadastroFase;
    long idBtnExcluirJdgCadastroFase;
    long idBtnLocalizarJdgCadastroFase;
    long idBtnSalvarJdgCadastroMotivo;
    long idBtnExcluirJdgCadastroMotivo;
    long idBtnLocalizarJdgCadastroMotivo;
    long idBtnSalvarJdgCadastroUsuario;
    long idBtnExcluirJdgCadastroUsuario;
    long idBtnLocalizarJdgCadastroUsuario;
    long idBtnSalvarJdgCadastroPrioridade;
    long idBtnExcluirJdgCadastroPrioridade;
    long idBtnLocalizarJdgCadastroPrioridade;
    long idBtnSalvarJdgPermissoesUsuario;

    public JdgPermissoesUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        Validacao.setaPermissoes(this.getClass().getName(), this.jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        chkExcluirCliente = new javax.swing.JCheckBox();
        chkSalvarCliente = new javax.swing.JCheckBox();
        chkLocalizarCliente = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        chkExcluirCidade = new javax.swing.JCheckBox();
        chkSalvarCidade = new javax.swing.JCheckBox();
        chkLocalizarCidade = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        chkExcluirCadastroProjeto = new javax.swing.JCheckBox();
        chkSalvarCadastroProjeto = new javax.swing.JCheckBox();
        chkLocalizarCadastroProjeto = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        chkExcluirCadastroFase = new javax.swing.JCheckBox();
        chkSalvarCadastroFase = new javax.swing.JCheckBox();
        chkLocalizarCadastroFase = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        chkExcluirCadastroUsuario = new javax.swing.JCheckBox();
        chkSalvarCadastroUsuario = new javax.swing.JCheckBox();
        chkLocalizarCadastroUsuario = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        chkExcluirCadastroMotivo = new javax.swing.JCheckBox();
        chkSalvarCadastroMotivo = new javax.swing.JCheckBox();
        chkLocalizarCadastroMotivo = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        chkExcluirCadastroPrioridade = new javax.swing.JCheckBox();
        chkSalvarCadastroPrioridade = new javax.swing.JCheckBox();
        chkLocalizarCadastroPrioridade = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        chkSalvarPermissoesUsuario = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        chkSalvarAlteracaoSenha = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        chkDesativarAuditoria = new javax.swing.JCheckBox();
        chkAtivarAuditoria = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        tfdUsuario = new javax.swing.JTextField();
        btnLocalizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help Easy - Cadastro de cidade");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permissões de Usuário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(0, 51, 255))); // NOI18N

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setName("btnSalvar"); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_Schutdown16.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastros", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCliente.setText("Excluir");

        chkSalvarCliente.setText("Salvar");

        chkLocalizarCliente.setText("Localizar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCliente)
                    .addComponent(chkSalvarCliente)
                    .addComponent(chkExcluirCliente))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(chkLocalizarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkExcluirCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cidade", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCidade.setText("Excluir");

        chkSalvarCidade.setText("Salvar");

        chkLocalizarCidade.setText("Localizar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCidade)
                    .addComponent(chkSalvarCidade)
                    .addComponent(chkExcluirCidade))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(chkLocalizarCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExcluirCidade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerência", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de projeto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCadastroProjeto.setText("Excluir");

        chkSalvarCadastroProjeto.setText("Salvar");

        chkLocalizarCadastroProjeto.setText("Localizar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCadastroProjeto)
                    .addComponent(chkSalvarCadastroProjeto)
                    .addComponent(chkExcluirCadastroProjeto))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(chkLocalizarCadastroProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCadastroProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExcluirCadastroProjeto))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de fase", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCadastroFase.setText("Excluir");

        chkSalvarCadastroFase.setText("Salvar");

        chkLocalizarCadastroFase.setText("Localizar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCadastroFase)
                    .addComponent(chkSalvarCadastroFase)
                    .addComponent(chkExcluirCadastroFase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(chkLocalizarCadastroFase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCadastroFase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExcluirCadastroFase))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de usuário", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCadastroUsuario.setText("Excluir");

        chkSalvarCadastroUsuario.setText("Salvar");

        chkLocalizarCadastroUsuario.setText("Localizar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCadastroUsuario)
                    .addComponent(chkSalvarCadastroUsuario)
                    .addComponent(chkExcluirCadastroUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(chkLocalizarCadastroUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCadastroUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExcluirCadastroUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de motivo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCadastroMotivo.setText("Excluir");

        chkSalvarCadastroMotivo.setText("Salvar");

        chkLocalizarCadastroMotivo.setText("Localizar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCadastroMotivo)
                    .addComponent(chkSalvarCadastroMotivo)
                    .addComponent(chkExcluirCadastroMotivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(chkLocalizarCadastroMotivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCadastroMotivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkExcluirCadastroMotivo)
                .addContainerGap())
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de prioridade", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkExcluirCadastroPrioridade.setText("Excluir");

        chkSalvarCadastroPrioridade.setText("Salvar");

        chkLocalizarCadastroPrioridade.setText("Localizar");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLocalizarCadastroPrioridade)
                    .addComponent(chkSalvarCadastroPrioridade)
                    .addComponent(chkExcluirCadastroPrioridade))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(chkLocalizarCadastroPrioridade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkSalvarCadastroPrioridade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExcluirCadastroPrioridade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Permissões de usuário", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkSalvarPermissoesUsuario.setText("Salvar");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkSalvarPermissoesUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(chkSalvarPermissoesUsuario)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alteração de senha", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkSalvarAlteracaoSenha.setText("Salvar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(chkSalvarAlteracaoSenha)
                .addGap(0, 83, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(chkSalvarAlteracaoSenha)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parâmetros do sistema", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        chkDesativarAuditoria.setText("desativar auditoria");

        chkAtivarAuditoria.setText("Ativar auditoria");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAtivarAuditoria)
                    .addComponent(chkDesativarAuditoria))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(chkAtivarAuditoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDesativarAuditoria))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Usuário:");

        tfdUsuario.setEditable(false);

        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lupa3.png"))); // NOI18N
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 28, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(307, 307, 307))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(tfdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarNovasPermissoes();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed

        usuarios.setLogin("");
        usuarios.setNome("");
        JdgListaUsuario listaUsuario = new JdgListaUsuario(null, true, usuarios);
        listaUsuario.setVisible(true);

        tfdUsuario.setText(usuarios.getLogin());
        if (tfdUsuario.getText().length() > 0) {
            listarpermissoes();
        }
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        listarpermissoes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listarpermissoes() {
        limparPermissoes();
        UsuarioPermissaoTelaAcoes usuarioPermissaoTelaAcoes = new UsuarioPermissaoTelaAcoes();
        ArrayList<UsuarioPermissaoTelaAcoes> permissoes = new ArrayList<>();
        PermissoesDAO permissoesDAO = new PermissoesDAO();
        permissoes = permissoesDAO.listarPermissoes(usuarios);
        for (int i = 0; i < permissoes.size(); i++) {

            if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCidade.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCidade.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCidade.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCliente.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCliente.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCliente.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgAlteracaoSenha")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarAlteracaoSenha.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgParametrosSistema")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnEnableAuditoria")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkAtivarAuditoria.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgParametrosSistema")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnDisableAuditoria")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkDesativarAuditoria.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCadastroFase.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCadastroFase.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCadastroFase.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCadastroProjeto.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCadastroProjeto.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCadastroProjeto.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCadastroMotivo.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCadastroMotivo.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCadastroMotivo.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCadastroUsuario.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCadastroUsuario.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCadastroUsuario.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarCadastroPrioridade.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkLocalizarCadastroPrioridade.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkExcluirCadastroPrioridade.setSelected(true);

            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgPermissoesUsuario")
                    && permissoes.get(i).getPermiteAcesso() == 'S'
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                chkSalvarPermissoesUsuario.setSelected(true);
            }

            if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroCidade = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroCidade);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroCliente = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroCliente);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgAlteracaoSenha")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgAlteracaoSenha = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgAlteracaoSenha);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroFase = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroFase);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroProjeto = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroProjeto);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroMotivo = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroMotivo);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroUsuario = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroUsuario);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgCadastroPrioridade = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgCadastroPrioridade);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgPermissoesUsuario")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgPermissoesUsuario = permissoes.get(i).getUsuarioPermissaoTela().getId();
                System.out.println(idJdgPermissoesUsuario);
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgParametrosSistema")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idJdgParametrosSistema = permissoes.get(i).getUsuarioPermissaoTela().getId();
            }

            if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroCidade = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroCidade = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCidade")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroCidade = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroCliente = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroCliente = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroCliente")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroCliente = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgAlteracaoSenha")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgAlteracaoSenha = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgParametrosSistema")
                    && permissoes.get(i).getAcao().equals("btnEnableAuditoria")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnEnableAuditoriaParametrosSistema = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgParametrosSistema")
                    && permissoes.get(i).getAcao().equals("btnDisableAuditoria")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnDisableAuditoriaParametrosSistema = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroFase = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroFase = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroFase")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroFase = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroProjeto = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroProjeto = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroProjeto")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroProjeto = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroMotivo = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroMotivo = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroMotivo")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroMotivo = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroUsuario = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroUsuario = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroUsuario")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroUsuario = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgCadastroPrioridade = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getAcao().equals("btnLocalizar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnLocalizarJdgCadastroPrioridade = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgCadastroPrioridade")
                    && permissoes.get(i).getAcao().equals("btnExcluir")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnExcluirJdgCadastroPrioridade = permissoes.get(i).getId();
            } else if (permissoes.get(i).getUsuarioPermissaoTela().getTela().equals("janelas.JdgPermissoesUsuario")
                    && permissoes.get(i).getAcao().equals("btnSalvar")
                    && permissoes.get(i).getUsuarioPermissaoTela().getUsuario().getId() == usuarios.getId()) {
                idBtnSalvarJdgPermissoesUsuario = permissoes.get(i).getId();
            }

        }

    }

    private void salvarNovasPermissoes() {
        try {
            UsuarioPermissaoTela usuarioPermissaoTela = new UsuarioPermissaoTela();
            UsuarioPermissaoTelaAcoes usuarioPermissaoTelaAcoes = new UsuarioPermissaoTelaAcoes();
            UsuarioPermissaoTelaAcoesDAO usuarioPermissaoTelaAcoesDAO = new UsuarioPermissaoTelaAcoesDAO();
            usuarioPermissaoTelaAcoes.setId(idBtnEnableAuditoriaParametrosSistema);
            usuarioPermissaoTela.setId(idJdgParametrosSistema);

            usuarioPermissaoTela.setUsuario(usuarios);
            usuarioPermissaoTela.setPermiteAcesso('S');

            usuarioPermissaoTelaAcoes.setAcao("btnEnableAuditoria");
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            if (chkAtivarAuditoria.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setId(idBtnEnableAuditoriaParametrosSistema);
            usuarioPermissaoTela.setId(idJdgParametrosSistema);
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setId(idBtnDisableAuditoriaParametrosSistema);

            usuarioPermissaoTela.setUsuario(usuarios);
            usuarioPermissaoTela.setPermiteAcesso('S');
            usuarioPermissaoTelaAcoes.setAcao("btnDisableAuditoria");
            if (chkDesativarAuditoria.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTela.setId(idJdgAlteracaoSenha);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgAlteracaoSenha);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarAlteracaoSenha.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            //--------------------------------------------------------------
            usuarioPermissaoTela.setId(idJdgCadastroCidade);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroCidade);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCidade.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroCidade);
            if (chkExcluirCidade.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroCidade);
            if (chkLocalizarCidade.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//---------------------------------------        

            usuarioPermissaoTela.setId(idJdgCadastroCliente);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroCliente);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCliente.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroCliente);
            if (chkExcluirCliente.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroCliente);
            if (chkLocalizarCliente.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//--------------------------------

            usuarioPermissaoTela.setId(idJdgCadastroMotivo);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroMotivo);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCadastroMotivo.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroMotivo);
            if (chkExcluirCadastroMotivo.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroMotivo);
            if (chkLocalizarCadastroMotivo.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//----------------------------------------

            usuarioPermissaoTela.setId(idJdgCadastroProjeto);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroProjeto);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCadastroProjeto.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroProjeto);
            if (chkExcluirCadastroProjeto.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroProjeto);
            if (chkLocalizarCadastroMotivo.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//-------------------------------------

            usuarioPermissaoTela.setId(idJdgCadastroUsuario);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroUsuario);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCadastroUsuario.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroUsuario);
            if (chkExcluirCadastroUsuario.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroUsuario);
            if (chkLocalizarCadastroUsuario.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//-------------------------

            usuarioPermissaoTela.setId(idJdgCadastroFase);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroFase);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCadastroFase.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroFase);
            if (chkExcluirCadastroFase.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroFase);
            if (chkLocalizarCadastroFase.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//----------------------------

            usuarioPermissaoTela.setId(idJdgCadastroPrioridade);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgCadastroPrioridade);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarCadastroPrioridade.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnExcluir");
            usuarioPermissaoTelaAcoes.setId(idBtnExcluirJdgCadastroPrioridade);
            if (chkExcluirCadastroPrioridade.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);

            usuarioPermissaoTelaAcoes.setAcao("btnLocalizar");
            usuarioPermissaoTelaAcoes.setId(idBtnLocalizarJdgCadastroPrioridade);
            if (chkLocalizarCadastroPrioridade.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
//---------------------------------
            usuarioPermissaoTela.setId(idJdgPermissoesUsuario);
            usuarioPermissaoTelaAcoes.setId(idBtnSalvarJdgPermissoesUsuario);
            usuarioPermissaoTelaAcoes.setAcao("btnSalvar");
            if (chkSalvarPermissoesUsuario.isSelected()) {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('S');
            } else {
                usuarioPermissaoTelaAcoes.setPermiteAcesso('N');
            }
            usuarioPermissaoTelaAcoes.setUsuarioPermissaoTela(usuarioPermissaoTela);
            usuarioPermissaoTelaAcoesDAO.salvar(usuarioPermissaoTelaAcoes);
            
            JOptionPane.showMessageDialog(rootPane, "Alterações de permissões salva com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao gravar as permissões\n" + e);
        }

    }

    private void limparPermissoes() {
        chkAtivarAuditoria.setSelected(false);
        chkDesativarAuditoria.setSelected(false);
        chkExcluirCadastroFase.setSelected(false);
        chkExcluirCadastroMotivo.setSelected(false);
        chkExcluirCadastroPrioridade.setSelected(false);
        chkExcluirCadastroProjeto.setSelected(false);
        chkExcluirCadastroUsuario.setSelected(false);
        chkExcluirCidade.setSelected(false);
        chkExcluirCliente.setSelected(false);
        chkLocalizarCadastroFase.setSelected(false);
        chkLocalizarCadastroMotivo.setSelected(false);
        chkLocalizarCadastroPrioridade.setSelected(false);
        chkLocalizarCadastroProjeto.setSelected(false);
        chkLocalizarCadastroUsuario.setSelected(false);
        chkLocalizarCidade.setSelected(false);
        chkLocalizarCliente.setSelected(false);
        chkSalvarAlteracaoSenha.setSelected(false);
        chkSalvarCadastroFase.setSelected(false);
        chkSalvarCadastroMotivo.setSelected(false);
        chkSalvarCadastroPrioridade.setSelected(false);
        chkSalvarCadastroUsuario.setSelected(false);
        chkSalvarCadastroProjeto.setSelected(false);
        chkSalvarCidade.setSelected(false);
        chkSalvarCliente.setSelected(false);
        chkSalvarPermissoesUsuario.setSelected(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdgPermissoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdgPermissoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdgPermissoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdgPermissoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdgPermissoesUsuario dialog = new JdgPermissoesUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivarAuditoria;
    private javax.swing.JCheckBox chkDesativarAuditoria;
    private javax.swing.JCheckBox chkExcluirCadastroFase;
    private javax.swing.JCheckBox chkExcluirCadastroMotivo;
    private javax.swing.JCheckBox chkExcluirCadastroPrioridade;
    private javax.swing.JCheckBox chkExcluirCadastroProjeto;
    private javax.swing.JCheckBox chkExcluirCadastroUsuario;
    private javax.swing.JCheckBox chkExcluirCidade;
    private javax.swing.JCheckBox chkExcluirCliente;
    private javax.swing.JCheckBox chkLocalizarCadastroFase;
    private javax.swing.JCheckBox chkLocalizarCadastroMotivo;
    private javax.swing.JCheckBox chkLocalizarCadastroPrioridade;
    private javax.swing.JCheckBox chkLocalizarCadastroProjeto;
    private javax.swing.JCheckBox chkLocalizarCadastroUsuario;
    private javax.swing.JCheckBox chkLocalizarCidade;
    private javax.swing.JCheckBox chkLocalizarCliente;
    private javax.swing.JCheckBox chkSalvarAlteracaoSenha;
    private javax.swing.JCheckBox chkSalvarCadastroFase;
    private javax.swing.JCheckBox chkSalvarCadastroMotivo;
    private javax.swing.JCheckBox chkSalvarCadastroPrioridade;
    private javax.swing.JCheckBox chkSalvarCadastroProjeto;
    private javax.swing.JCheckBox chkSalvarCadastroUsuario;
    private javax.swing.JCheckBox chkSalvarCidade;
    private javax.swing.JCheckBox chkSalvarCliente;
    private javax.swing.JCheckBox chkSalvarPermissoesUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField tfdUsuario;
    // End of variables declaration//GEN-END:variables
}
